defaults:
  - dataset: synth_linear
  - model: route_a_head
  - logging: offline
  - experiment: route_a
  - _self_

seed: 123
n_support: 48
n_query: 32
p: 16
d_proj: 12
tau: 0.5
lambda: 0.01
noise: 0.1


